# Generated by Django 2.1.1 on 2018-10-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price')),
                ('barcode', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Barcode')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=20, verbose_name='Barcode')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='TotalPrice')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'PurchaseItem',
                'verbose_name_plural': 'PurchaseItems',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('cart', models.BooleanField(verbose_name='Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'PurchaseOrders',
            },
        ),
        migrations.CreateModel(
            name='PurchasePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Value')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.PaymentMethod', verbose_name='PaymentMethod')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PurchaseOrder', verbose_name='PurchaseOrder')),
            ],
            options={
                'verbose_name': 'PurchasePaymentMethod',
                'verbose_name_plural': 'PurchasePaymentMethods',
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PurchaseOrder', verbose_name='PurchaseOrder'),
        ),
    ]
