# Generated by Django 2.0.7 on 2018-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='barcode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
