# Generated by Django 2.0.7 on 2018-09-16 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180916_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'PaymentMethod', 'verbose_name_plural': 'PaymentMethods'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'PurchaseItem', 'verbose_name_plural': 'PurchaseItems'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'PurchaseOrder', 'verbose_name_plural': 'PurchaseOrders'},
        ),
        migrations.AlterModelOptions(
            name='purchasepaymentmethod',
            options={'verbose_name': 'PurchasePaymentMethod', 'verbose_name_plural': 'PurchasePaymentMethods'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='barcode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PurchaseOrder', verbose_name='PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='TotalPrice'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='cart',
            field=models.BooleanField(verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='purchasepaymentmethod',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.PaymentMethod', verbose_name='PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='purchasepaymentmethod',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PurchaseOrder', verbose_name='PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='purchasepaymentmethod',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Value'),
        ),
    ]
